#pragma once

#ifndef _ASCII_MAP_HXX_
#define _ASCII_MAP_HXX_


#define ASCII_BR_BAR         '\001' //
#define ASCII_BL_BAR         '\002' //
#define ASCII_UR_BAR         '\002' //
#define ASCII_UL_BAR         '\002' //
#define ASCII_VT_BAR         '\005' //
#define ASCII_HZ_BAR         '\006' //
#define ASCII_CROSS_BAR      '\020' //
#define ASCII_UT_BAR         '\025' //
#define ASCII_BT_BAR         '\026' //
#define ASCII_LT_BAR         '\027' //
#define ASCII_RT_BAR         '\031' //
#define ASCII_RIGHT_TRIANGLE '\021' //
#define ASCII_UP_TRIANGLE    '\036' //
#define ASCII_DOWN_TRIANGLE  '\037' //

#endif