#pragma once

#ifndef _ASCII_MAP_HXX_
#define _ASCII_MAP_HXX_

namespace Ascii {
	constexpr char BR_BAR         = '\001'; //
	constexpr char BL_BAR         = '\002'; //
	constexpr char UR_BAR         = '\002'; //
	constexpr char UL_BAR         = '\002'; //
	constexpr char VT_BAR         = '\005'; //
	constexpr char HZ_BAR         = '\006'; //
	constexpr char CROSS_BAR      = '\020'; //
	constexpr char UT_BAR         = '\025'; //
	constexpr char BT_BAR         = '\026'; //
	constexpr char LT_BAR         = '\027'; //
	constexpr char RT_BAR         = '\031'; //
	constexpr char RIGHT_TRIANGLE = '\021'; //
	constexpr char UP_TRIANGLE    = '\036'; //
	constexpr char DOWN_TRIANGLE  = '\037'; //
}

#endif